package elgamal

import (
	"crypto"
	"crypto/rand"
	"encoding/binary"
	"errors"
	"fmt"
	"io"
	"math/big"
)

// PublicKey represents an ElGamal public key
type PublicKey struct {
	P *big.Int // prime modulus
	G *big.Int // generator
	Y *big.Int // public key value
}

// Encrypt encrypts a message using ElGamal encryption for the public key.
//
// Important: Messages are treated as numeric values (big.Int). The numeric value
// is preserved during encryption/decryption, but the byte-level representation
// may change. Specifically, leading zero bytes in the input will be stripped when
// converting to big.Int and will not be restored during decryption.
//
// Example: []byte{0x00, 0x00, 0x01, 0x02} encrypts and decrypts correctly, but
// the decrypted result will be []byte{0x01, 0x02} (same numeric value, different
// byte representation).
//
// Empty messages ([]byte{}) are supported and encrypt to the numeric value 0,
// which decrypts back to []byte{}.
//
// For arbitrary binary data where exact byte sequences must be preserved, use a
// higher-level protocol that includes message length encoding.
func (p *PublicKey) Encrypt(randReader io.Reader, msg []byte) (ciphertext []byte, err error) {
	if randReader == nil {
		randReader = rand.Reader
	}
	// Convert msg to big.Int
	m := new(big.Int).SetBytes(msg)

	// Encrypt the message
	c1, c2, err := Encrypt(randReader, p, m)
	if err != nil {
		return nil, err
	}

	// Serialize c1 and c2 with fixed length equal to the modulus size
	// This ensures equal-length encoding as required by the design specification
	modulusBytes := (p.P.BitLen() + 7) / 8 // Convert bit length to byte length
	c1Bytes := c1.FillBytes(make([]byte, modulusBytes))
	c2Bytes := c2.FillBytes(make([]byte, modulusBytes))

	ciphertext = append(c1Bytes, c2Bytes...)
	return ciphertext, nil
}

// MarshalBinary encodes the PublicKey to binary format
// Format: [len(P)][P][len(G)][G][len(Y)][Y] where lengths are 4-byte big-endian
func (pub *PublicKey) MarshalBinary() ([]byte, error) {
	if pub == nil || pub.P == nil || pub.G == nil || pub.Y == nil {
		return nil, errors.New("invalid public key: nil fields")
	}

	pBytes := pub.P.Bytes()
	gBytes := pub.G.Bytes()
	yBytes := pub.Y.Bytes()

	// Validate lengths fit in uint32 to prevent overflow in serialization
	// This should never occur with keys generated by GenerateKey (max 16384 bits)
	// but provides defense against malformed keys
	if uint64(len(pBytes)) > 0xFFFFFFFF || uint64(len(gBytes)) > 0xFFFFFFFF || uint64(len(yBytes)) > 0xFFFFFFFF {
		return nil, errors.New("key component too large for serialization")
	}

	// Calculate total size: 3 * 4 bytes (lengths) + data
	size := 12 + len(pBytes) + len(gBytes) + len(yBytes)
	result := make([]byte, size)

	offset := 0
	// Write P
	binary.BigEndian.PutUint32(result[offset:], uint32(len(pBytes)))
	offset += 4
	copy(result[offset:], pBytes)
	offset += len(pBytes)

	// Write G
	binary.BigEndian.PutUint32(result[offset:], uint32(len(gBytes)))
	offset += 4
	copy(result[offset:], gBytes)
	offset += len(gBytes)

	// Write Y
	binary.BigEndian.PutUint32(result[offset:], uint32(len(yBytes)))
	offset += 4
	copy(result[offset:], yBytes)

	return result, nil
}

// UnmarshalBinary decodes a PublicKey from binary format
func (pub *PublicKey) UnmarshalBinary(data []byte) error {
	if len(data) < 12 {
		return errors.New("data too short for public key")
	}

	offset := 0

	// Read P
	pLen := binary.BigEndian.Uint32(data[offset:])
	offset += 4
	if offset+int(pLen) > len(data) {
		return errors.New("invalid P length")
	}
	pub.P = new(big.Int).SetBytes(data[offset : offset+int(pLen)])
	offset += int(pLen)

	// Read G
	if offset+4 > len(data) {
		return errors.New("data too short for G length")
	}
	gLen := binary.BigEndian.Uint32(data[offset:])
	offset += 4
	if offset+int(gLen) > len(data) {
		return errors.New("invalid G length")
	}
	pub.G = new(big.Int).SetBytes(data[offset : offset+int(gLen)])
	offset += int(gLen)

	// Read Y
	if offset+4 > len(data) {
		return errors.New("data too short for Y length")
	}
	yLen := binary.BigEndian.Uint32(data[offset:])
	offset += 4
	if offset+int(yLen) > len(data) {
		return errors.New("invalid Y length")
	}
	pub.Y = new(big.Int).SetBytes(data[offset : offset+int(yLen)])

	return nil
}

// PrivateKey represents an ElGamal private key
type PrivateKey struct {
	PublicKey
	X *big.Int // private key value
}

// Decrypt implements crypto.Decrypter.
func (p *PrivateKey) Decrypt(randReader io.Reader, msg []byte, opts crypto.DecrypterOpts) (plaintext []byte, err error) {
	// Note: randReader is unused because ElGamal decryption is deterministic.
	// The parameter is required by the crypto.Decrypter interface.

	// Split msg into c1 and c2
	if len(msg) < 2 {
		return nil, errors.New("ciphertext too short")
	}
	if len(msg)%2 != 0 {
		return nil, errors.New("ciphertext must have even length")
	}

	// Split at midpoint - both components have equal length (modulus size)
	mid := len(msg) / 2
	c1 := new(big.Int).SetBytes(msg[:mid])
	c2 := new(big.Int).SetBytes(msg[mid:])

	// Decrypt and convert result to bytes
	plainInt, err := Decrypt(p, c1, c2)
	if err != nil {
		return nil, fmt.Errorf("decryption failed: %w", err)
	}
	return plainInt.Bytes(), nil
}

// Public implements crypto.Signer.
func (p *PrivateKey) Public() crypto.PublicKey {
	return &p.PublicKey
}

// MarshalBinary encodes the PrivateKey to binary format
// Format: [PublicKey encoding][len(X)][X]
func (priv *PrivateKey) MarshalBinary() ([]byte, error) {
	if priv == nil || priv.X == nil {
		return nil, errors.New("invalid private key: nil fields")
	}

	// Marshal the public key part
	pubBytes, err := priv.PublicKey.MarshalBinary()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal public key: %w", err)
	}

	xBytes := priv.X.Bytes()

	// Validate X length fits in uint32 to prevent overflow
	// This should never occur with keys generated by GenerateKey (max 16384 bits)
	if uint64(len(xBytes)) > 0xFFFFFFFF {
		return nil, errors.New("private key component too large for serialization")
	}

	// Total size: public key + 4 bytes (X length) + X data
	result := make([]byte, len(pubBytes)+4+len(xBytes))

	offset := 0
	copy(result[offset:], pubBytes)
	offset += len(pubBytes)

	// Write X
	binary.BigEndian.PutUint32(result[offset:], uint32(len(xBytes)))
	offset += 4
	copy(result[offset:], xBytes)

	return result, nil
}

// UnmarshalBinary decodes a PrivateKey from binary format
func (priv *PrivateKey) UnmarshalBinary(data []byte) error {
	if len(data) < 16 { // Minimum: 12 bytes for public key + 4 bytes for X length
		return errors.New("data too short for private key")
	}

	// First, unmarshal the public key part
	// We need to determine where the public key ends
	// We'll unmarshal into a temporary public key first
	tempPub := &PublicKey{}
	if err := tempPub.UnmarshalBinary(data); err != nil {
		return fmt.Errorf("failed to unmarshal public key: %w", err)
	}

	// Calculate the size of the public key encoding
	pubBytes, err := tempPub.MarshalBinary()
	if err != nil {
		return fmt.Errorf("failed to re-marshal public key: %w", err)
	}
	pubSize := len(pubBytes)

	if pubSize+4 > len(data) {
		return errors.New("data too short for X length")
	}

	// Copy the public key fields
	priv.PublicKey = *tempPub

	// Read X
	offset := pubSize
	xLen := binary.BigEndian.Uint32(data[offset:])
	offset += 4
	if offset+int(xLen) > len(data) {
		return errors.New("invalid X length")
	}
	priv.X = new(big.Int).SetBytes(data[offset : offset+int(xLen)])

	return nil
}

// GenerateKey generates a new ElGamal key pair
func GenerateKey(random io.Reader, bitSize int) (*PrivateKey, error) {
	if bitSize < 512 {
		return nil, errors.New("key size must be at least 512 bits")
	}
	// Maximum key size ensures serialization with uint32 length fields remains valid
	// (uint32 max = 4,294,967,295 bytes = ~34 billion bits, but we use a practical limit)
	if bitSize > 16384 {
		return nil, errors.New("key size must not exceed 16384 bits")
	}

	// Generate a prime p
	p, err := rand.Prime(random, bitSize)
	if err != nil {
		return nil, fmt.Errorf("failed to generate prime: %w", err)
	}

	// Use 2 as generator (simple but works for most primes)
	g := big.NewInt(2)

	// Generate private key x in range [1, p-2]
	pMinus2 := new(big.Int).Sub(p, big.NewInt(2))
	x, err := rand.Int(random, pMinus2)
	if err != nil {
		return nil, fmt.Errorf("failed to generate private key: %w", err)
	}
	x.Add(x, big.NewInt(1)) // ensure x >= 1

	// Calculate public key y = g^x mod p
	y := new(big.Int).Exp(g, x, p)

	return &PrivateKey{
		PublicKey: PublicKey{P: p, G: g, Y: y},
		X:         x,
	}, nil
}

// Encrypt encrypts a message using ElGamal encryption
func Encrypt(random io.Reader, pub *PublicKey, message *big.Int) (*big.Int, *big.Int, error) {
	// Validate inputs to prevent nil pointer dereference
	if pub == nil || message == nil {
		return nil, nil, errors.New("public key and message must not be nil")
	}

	// Validate message is in valid range [0, p-1)
	if message.Sign() < 0 || message.Cmp(pub.P) >= 0 {
		return nil, nil, errors.New("message must be in range [0, p-1)")
	}

	// Generate random k in range [1, p-2]
	pMinus2 := new(big.Int).Sub(pub.P, big.NewInt(2))
	k, err := rand.Int(random, pMinus2)
	if err != nil {
		return nil, nil, fmt.Errorf("failed to generate random k: %w", err)
	}
	k.Add(k, big.NewInt(1))

	// Calculate c1 = g^k mod p
	c1 := new(big.Int).Exp(pub.G, k, pub.P)

	// Calculate c2 = m * y^k mod p
	yk := new(big.Int).Exp(pub.Y, k, pub.P)
	c2 := new(big.Int).Mul(message, yk)
	c2.Mod(c2, pub.P)

	return c1, c2, nil
}

// Decrypt decrypts a ciphertext using ElGamal decryption
func Decrypt(priv *PrivateKey, c1, c2 *big.Int) (*big.Int, error) {
	// Validate inputs to prevent nil pointer dereference
	if priv == nil {
		return nil, errors.New("private key must not be nil")
	}
	if c1 == nil || c2 == nil {
		return nil, errors.New("ciphertext components must not be nil")
	}

	// Calculate c1^x mod p
	c1x := new(big.Int).Exp(c1, priv.X, priv.P)

	// Calculate modular inverse of c1^x
	inv := new(big.Int).ModInverse(c1x, priv.P)
	if inv == nil {
		// No modular inverse exists (e.g., c1 = 0 or gcd(c1^x, p) != 1)
		return nil, errors.New("invalid ciphertext: no modular inverse exists")
	}

	// Calculate message = c2 * inv mod p
	message := new(big.Int).Mul(c2, inv)
	message.Mod(message, priv.P)

	return message, nil
}
